version: '3.4'
services:
  db:
    image: leoneoliveira/mysql-rest-with-spring-boot
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: rest_with_spring_boot
    ports:
      - "3308:3306"
    networks:
      - spring-network
  rest-with-spring-boot:
    image: leoneoliveira/rest-with-spring-boot
    restart: always
    build: ./SpringBootStudy
    working_dir: /SpringBootStudy
    environment:
      TZ: America/Sao_Paulo
      SPRING_BOOT_ENVIRONMENT: Production
    volumes:
      - ./SpringBootStudy:/SpringBootStudy
      - ~/.m2:/root/.m2
    ports:
      - "8080:8080"
    command: mvn clean spring-boot:run
    links:
      - db
    depends_on:
      - db
    networks:
      - spring-network
networks:
    spring-network:
        driver: bridge